// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "multipart/form-data"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/transcribe": {
            "post": {
                "description": "Receives an audio file upload, transcribes and analyzes it with Google Gemini,\nand persists the result in RavenDB.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transcription"
                ],
                "summary": "Transcribe an audio file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file (mp3, mp4, wav, m4a, ogg, webm, flac — max 25MB)",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.TranscriptionRecord"
                        }
                    },
                    "400": {
                        "description": "Missing 'audio' field",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "File exceeds MAX_UPLOAD_BYTES",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error or RavenDB failure",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream API failure from Gemini",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Required AI provider is not configured",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transcriptions": {
            "get": {
                "description": "Returns paginated transcriptions ordered by creation date descending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transcription"
                ],
                "summary": "List stored transcriptions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of records to return (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.TranscriptionRecord"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.TranscriptionRecord": {
            "type": "object",
            "properties": {
                "Id": {
                    "description": "ID is auto-assigned by RavenDB as \"transcriptions/N-A\".",
                    "type": "string",
                    "example": "transcriptions/1-A"
                },
                "audioDuration": {
                    "type": "number",
                    "example": 47.3
                },
                "audioFilename": {
                    "description": "Audio file metadata.",
                    "type": "string",
                    "example": "meeting.mp3"
                },
                "createdAt": {
                    "description": "Metadata.",
                    "type": "string"
                },
                "fileSizeBytes": {
                    "type": "integer",
                    "example": 2097152
                },
                "keyPoints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language": {
                    "type": "string",
                    "example": "en"
                },
                "sentiment": {
                    "type": "string",
                    "example": "positive"
                },
                "summary": {
                    "description": "AI analysis from Google Gemini — stored as nested document, schema-free.",
                    "type": "string"
                },
                "transcript": {
                    "description": "Transcription result from Gemini audio understanding.",
                    "type": "string",
                    "example": "Hello, this is a test recording..."
                }
            }
        },
        "handler.ErrorResponse": {
            "description": "Standardized error response",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "audio field is required"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "example.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Audio Transcription API",
	Description:      "POC: receives audio, transcribes and analyzes with Google Gemini, persists in RavenDB.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
